[[redirects]]
  from = "/*"
  to = "/client/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/server/:splat"
  status = 200
  force = true

[build]
  command = "npm install"
  functions = "server/functions"

[build.environment]
  NODE_VERSION = "14"
